<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\AppSetting;

class AppSettingsSeeder extends Seeder
{
    public function run(): void
    {
        $settings = [
            // ======================
            // PAGE 1: APP SETTINGS (1st image)
            // ======================
            [
                'key' => 'file_upload_settings',
                'label' => 'File Upload Settings',
                'section' => 'Client Sign up Settings',
                'type' => 'text',
                'value' => '',
                'placeholder' => 'Configure file upload settings',
                'page' => 'app',
                'sort_order' => 1,
            ],
            [
                'key' => 'google_map_settings',
                'label' => 'Google Map Settings',
                'section' => 'Client Sign up Settings',
                'type' => 'text',
                'value' => '',
                'placeholder' => 'Configure Google Map settings',
                'page' => 'app',
                'sort_order' => 2,
            ],
            [
                'key' => 'date_format',
                'label' => 'Date Format',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => 'd-m-Y',
                'options' => json_encode(['d-m-Y', 'm-d-Y', 'Y-m-d', 'd/m/Y', 'm/d/Y', 'Y/m/d']),
                'page' => 'app',
                'sort_order' => 3,
            ],
            [
                'key' => 'session_driver',
                'label' => 'Session Driver',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => 'File',
                'options' => json_encode(['File', 'Database', 'Redis', 'Cookie']),
                'page' => 'app',
                'sort_order' => 4,
            ],
            [
                'key' => 'time_format',
                'label' => 'Time Format',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => '12 Hour(s)',
                'options' => json_encode(['12 Hour(s)', '24 Hour(s)']),
                'page' => 'app',
                'sort_order' => 5,
            ],
            [
                'key' => 'default_timezone',
                'label' => 'Default Timezone',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => 'Asia/Kolkata',
                'options' => json_encode(['Asia/Kolkata', 'UTC', 'America/New_York', 'Europe/London']),
                'page' => 'app',
                'sort_order' => 6,
            ],
            [
                'key' => 'default_currency',
                'label' => 'Default Currency',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => 'INR',
                'options' => json_encode(['INR', 'USD', 'EUR', 'GBP']),
                'page' => 'app',
                'sort_order' => 7,
            ],
            [
                'key' => 'language',
                'label' => 'Language',
                'section' => 'Date & Time',
                'type' => 'select',
                'value' => 'English',
                'options' => json_encode(['English', 'Hindi', 'Spanish', 'French']),
                'page' => 'app',
                'sort_order' => 8,
            ],
            [
                'key' => 'app_debug',
                'label' => 'App Debug',
                'section' => 'System Settings',
                'type' => 'checkbox',
                'value' => '1',
                'page' => 'app',
                'sort_order' => 9,
            ],
            [
                'key' => 'app_update',
                'label' => 'App Update',
                'section' => 'System Settings',
                'type' => 'checkbox',
                'value' => '1',
                'page' => 'app',
                'sort_order' => 10,
            ],
            [
                'key' => 'enable_cache',
                'label' => 'Enable Cache',
                'section' => 'System Settings',
                'type' => 'checkbox',
                'value' => '0',
                'page' => 'app',
                'sort_order' => 11,
            ],
            [
                'key' => 'datatable_row_limit',
                'label' => 'DataTable Row Limit',
                'section' => 'General',
                'type' => 'select',
                'value' => '50',
                'options' => json_encode(['10', '25', '50', '100', '200']),
                'page' => 'app',
                'sort_order' => 12,
            ],
            [
                'key' => 'employee_export',
                'label' => 'Employee can export data',
                'section' => 'General',
                'type' => 'checkbox',
                'value' => '1',
                'page' => 'app',
                'sort_order' => 13,
            ],

            // ======================
            // PAGE 2: CLIENT SIGNUP SETTINGS (2nd image)
            // ======================
            [
                'key' => 'allow_client_signup',
                'label' => 'Allow Client Signup',
                'section' => 'Client Signup Settings',
                'type' => 'checkbox',
                'value' => '1',
                'page' => 'client-signup',
                'sort_order' => 1,
            ],
            [
                'key' => 'admin_approval_required',
                'label' => 'Need admin approval after client signup',
                'section' => 'Client Signup Settings',
                'type' => 'checkbox',
                'value' => '1',
                'page' => 'client-signup',
                'sort_order' => 2,
            ],
            [
                'key' => 'client_verification',
                'label' => 'Email verification required',
                'section' => 'Client Signup Settings',
                'type' => 'checkbox',
                'value' => '0',
                'page' => 'client-signup',
                'sort_order' => 3,
            ],
            [
                'key' => 'min_password_length',
                'label' => 'Minimum Password Length',
                'section' => 'Client Signup Settings',
                'type' => 'number',
                'value' => '8',
                'min_value' => '6',
                'max_value' => '20',
                'unit' => 'characters',
                'page' => 'client-signup',
                'sort_order' => 4,
            ],

            // ======================
            // PAGE 3: FILE UPLOAD SETTINGS (3rd image)
            // ======================
            [
                'key' => 'server_upload_max_filesize',
                'label' => 'Server upload_max_filesize',
                'section' => 'Server Configuration',
                'type' => 'info',
                'value' => '1 GB',
                'description' => 'This is your server configuration',
                'page' => 'file-upload',
                'sort_order' => 1,
            ],
            [
                'key' => 'server_post_max_size',
                'label' => 'Server post_max_size',
                'section' => 'Server Configuration',
                'type' => 'info',
                'value' => '1 GB',
                'description' => 'This is your server configuration',
                'page' => 'file-upload',
                'sort_order' => 2,
            ],
            [
                'key' => 'max_file_size',
                'label' => 'Max File size for upload',
                'section' => 'Upload Limits',
                'type' => 'number',
                'value' => '10',
                'min_value' => '1',
                'max_value' => '1000',
                'unit' => 'MB',
                'placeholder' => 'Enter lower value than 1 GB',
                'page' => 'file-upload',
                'sort_order' => 3,
            ],
            [
                'key' => 'max_files_count',
                'label' => 'Max number of files for upload',
                'section' => 'Upload Limits',
                'type' => 'number',
                'value' => '10',
                'min_value' => '1',
                'max_value' => '100',
                'unit' => 'files',
                'page' => 'file-upload',
                'sort_order' => 4,
            ],
            [
                'key' => 'allowed_file_types',
                'label' => 'Allowed file types for upload',
                'section' => 'File Types',
                'type' => 'multiselect',
                'value' => json_encode(['image/*', 'application/pdf', 'text/plain']),
                'options' => json_encode([
                    'image/*',
                    'application/vnd.ms-excel',
                    'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                    'application/docx',
                    'application/pdf',
                    'text/plain',
                    'application/msword',
                    'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
                    'application/zip',
                    'application/x-zip-compressed',
                    'application/x-compressed',
                    'multipart/x-zip',
                    'xlsx',
                    'video/x-flv',
                    'video/mp4',
                    'application/x-mpegURL',
                    'video/MP2T',
                    'video/3gpp',
                    'video/quicktime',
                    'video/x-msvideo',
                    'application/x-stuffit',
                    '.sit',
                    'application/x-zip-compressed'
                ]),
                'placeholder' => 'Select allowed file types',
                'page' => 'file-upload',
                'sort_order' => 5,
            ],

            // ======================
            // PAGE 4: GOOGLE MAP SETTINGS (4th image)
            // ======================
            [
                'key' => 'google_map_key',
                'label' => 'Google map key',
                'section' => 'Google Map Settings',
                'type' => 'password',
                'value' => '',
                'placeholder' => 'e.g. AIzaSyDSi2bG7XXXXXXXXXXXXXXX',
                'description' => 'Leave blank to remove Google map key. Visit Google Cloud Console to get the keys.',
                'page' => 'google-map',
                'sort_order' => 1,
            ],
            [
                'key' => 'enable_google_maps',
                'label' => 'Enable Google Maps',
                'section' => 'Google Map Settings',
                'type' => 'checkbox',
                'value' => '0',
                'page' => 'google-map',
                'sort_order' => 2,
            ],
            [
                'key' => 'map_default_lat',
                'label' => 'Default Latitude',
                'section' => 'Google Map Settings',
                'type' => 'text',
                'value' => '28.6139',
                'placeholder' => 'e.g. 28.6139',
                'page' => 'google-map',
                'sort_order' => 3,
            ],
            [
                'key' => 'map_default_lng',
                'label' => 'Default Longitude',
                'section' => 'Google Map Settings',
                'type' => 'text',
                'value' => '77.2090',
                'placeholder' => 'e.g. 77.2090',
                'page' => 'google-map',
                'sort_order' => 4,
            ],
        ];

        foreach($settings as $setting){
            AppSetting::updateOrCreate(['key' => $setting['key']], $setting);
        }
    }
}
